### ISSUE TITLE
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)

### ISSUE THREAD

**Issue by dariusdev01** [andrewsegas/instaboost#24]
> Fill in all requirements *before* submitting an issue.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

## Issue with the same problem
- [x] I have searched for other issues with the same problem.

## Hosting
- [x] Is it a local machine?
yes , hp spectre 

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
Windows 10

## Running Mode
- [ ] instaboost.exe
- [X] example.py , mode (1,2,3,4 or 5)?  mode 0
- [ ] instaboost.py
- [ ] Other

## Python Version?
3.6

## Description

I have a tra
Traceback (most recent call last):
  File "C:\Users\darius\AppData\Local\Programs\Python\Python36-32\lib\site-packages\urllib3\connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "C:\Users\darius\AppData\Local\Programs\Python\Python36-32\lib\site-packages\urllib3\connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "C:\Users\darius\AppData\Local\Programs\Python\Python36-32\lib\site-packages\urllib3\connectionpool.py", line 850, in _validate_conn
    conn.connect()
  File "C:\Users\darius\AppData\Local\Programs\Python\Python36-32\lib\site-packages\urllib3\connection.py", line 326, in connect
    ssl_context=context)
  File "C:\Users\darius\AppData\Local\Programs\Python\Python36-32\lib\site-packages\urllib3\util\ssl_.py", line 329, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Users\darius\AppData\Local\Programs\Python\Python36-32\lib\ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "C:\Users\darius\AppData\Local\Programs\Python\Python36-32\lib\ssl.py", line 814, in __init__
    self.do_handshake()
  File "C:\Users\darius\AppData\Local\Programs\Python\Python36-32\lib\ssl.py", line 1068, in do_handshake
    self._sslobj.do_handshake()
  File "C:\Users\darius\AppData\Local\Programs\Python\Python36-32\lib\ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\darius\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests\adapters.py", line 440, in send
    timeout=timeout
  File "C:\Users\darius\AppData\Local\Programs\Python\Python36-32\lib\site-packages\urllib3\connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Users\darius\AppData\Local\Programs\Python\Python36-32\lib\site-packages\urllib3\util\retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)'),))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "example.py", line 59, in <module>
    UI = False)
  File "D:\instab\in\src\instabot.py", line 237, in __init__
    self.login()
  File "D:\instab\in\src\instabot.py", line 288, in login
    r = self.s.get(self.url)
  File "C:\Users\darius\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests\sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "C:\Users\darius\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests\sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\darius\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests\sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\darius\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests\adapters.py", line 506, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)'),))

And all the packages is well installed : 

D:\instab\in>pip install -r requirements.txt
Requirement already satisfied: requests in c:\users\darius\appdata\local\programs\python\python36-32\lib\site-packages (from -r requirements.txt (line 1))
Requirement already satisfied: fake-useragent in c:\users\darius\appdata\local\programs\python\python36-32\lib\site-packages (from -r requirements.txt (line 2))
Requirement already satisfied: idna<2.7,>=2.5 in c:\users\darius\appdata\local\programs\python\python36-32\lib\site-packages (from requests->-r requirements.txt (line 1))
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\users\darius\appdata\local\programs\python\python36-32\lib\site-packages (from requests->-r requirements.txt (line 1))
Requirement already satisfied: urllib3<1.23,>=1.21.1 in c:\users\darius\appdata\local\programs\python\python36-32\lib\site-packages (from requests->-r requirements.txt (line 1))
Requirement already satisfied: certifi>=2017.4.17 in c:\users\darius\appdata\local\programs\python\python36-32\lib\site-packages (from requests->-r requirements.txt (line 1))

Thank you for your time

**Comment by andrewsegas** [comment]
try to connect your instagram in your browser first and tell here what you got, please :)

**Comment by andrewsegas** [comment]
as i see your project is not updated, please update your project and check again. we fixed many things

**Comment by dariusdev01** [comment]
I redownloaded the lastest version but i still have the same error at the connection. It probably come from my computer (i downloaded a lot of cracked files). I will try on my other to see. If it is a computer problem i will try to reset windows and see if it is back. Thank you so much for having a look at my problem, if i can find how to solve this, i will post the solution here. Have a good day :)

**Comment by andrewsegas** [comment]
@dariusdev01 don't forget to send here the result

**Comment by dariusdev01** [comment]
The problem came from my computer , i don't know which file caused the problem but after a windows reset, everything works great .

**Comment by andrewsegas** [comment]
@dariusdev01 good to know, closing this issue :)
